from __future__ import annotations

import tempfile
import unittest
from pathlib import Path

from fastapi.testclient import TestClient

from app.database import connect, init_db
from app.main import create_app


class StaticUiTests(unittest.TestCase):
    def setUp(self) -> None:
        self.tmp = tempfile.TemporaryDirectory()
        self.db_path = str(Path(self.tmp.name) / "test.sqlite3")
        init_db(self.db_path)

    def tearDown(self) -> None:
        self.tmp.cleanup()

    def _counts(self) -> dict[str, int]:
        with connect(self.db_path) as conn:
            return {
                "documents": conn.execute("SELECT COUNT(*) AS count FROM json_documents").fetchone()["count"],
                "events": conn.execute("SELECT COUNT(*) AS count FROM document_events").fetchone()["count"],
            }

    def test_static_editor_shell_routes_are_public_and_do_not_mutate(self) -> None:
        client = TestClient(create_app(self.db_path))
        before = self._counts()

        index = client.get("/")
        app = client.get("/app")
        css = client.get("/static/styles.css")
        js = client.get("/static/app.js")
        favicon = client.get("/favicon.ico")

        self.assertEqual(index.status_code, 200)
        self.assertIn("text/html", index.headers["content-type"])
        self.assertIn("OpenJson", index.text)
        self.assertIn("authScreen", index.text)
        self.assertIn("projectScreen", index.text)
        self.assertIn("workspaceShell", index.text)
        self.assertIn("workspaceNameInput", index.text)
        self.assertIn("projectNameInput", index.text)
        self.assertIn("showCreateProjectButton", index.text)
        self.assertIn("cancelProjectCreateButton", index.text)
        self.assertIn("projectListPanel", index.text)
        self.assertIn("projectCreatePanel", index.text)
        self.assertIn("projectList", index.text)
        self.assertIn("projectInviteTokenInput", index.text)
        self.assertIn("JSON editor", index.text)
        self.assertIn("copyLinkButton", index.text)
        self.assertIn("editorFileInput", index.text)
        self.assertIn("conflictKeepLocalButton", index.text)
        self.assertIn("schemaPanel", index.text)
        self.assertIn("schemaSelect", index.text)
        self.assertIn("schemaMatchPanel", index.text)
        self.assertIn("zipFileInput", index.text)
        self.assertIn("zipImportOutput", index.text)
        self.assertIn("teamMembersOutput", index.text)
        self.assertIn("signupButton", index.text)
        self.assertIn("loginButton", index.text)
        self.assertIn("logoutButton", index.text)
        self.assertIn("createInviteButton", index.text)
        self.assertIn("acceptInviteButton", index.text)
        self.assertIn("inviteLinkInput", index.text)
        self.assertIn("copyInviteLinkButton", index.text)
        self.assertIn("autosaveToggle", index.text)
        self.assertIn("autoMergeToggle", index.text)
        self.assertIn("liveTextToggle", index.text)
        self.assertIn("commitLiveButton", index.text)
        self.assertIn("collaborationPanel", index.text)
        self.assertIn("commentsPanel", index.text)
        self.assertIn("commentsButton", index.text)
        self.assertIn("commentAnchorTypeSelect", index.text)
        self.assertIn("commentPathInput", index.text)
        self.assertIn("commentEventIdInput", index.text)
        self.assertIn("commentBodyInput", index.text)
        self.assertIn("createCommentThreadButton", index.text)
        self.assertNotIn("Create User", index.text)
        self.assertNotIn("Add Member", index.text)
        self.assertNotIn(">Actor<", index.text)
        self.assertNotIn(">Token<", index.text)
        self.assertNotIn("connectionForm", index.text)
        self.assertNotIn("actorIdInput", index.text)
        self.assertNotIn("projectIdInput", index.text)
        self.assertNotIn("tokenInput", index.text)
        self.assertEqual(app.status_code, 200)
        self.assertIn("text/html", app.headers["content-type"])
        self.assertEqual(css.status_code, 200)
        self.assertIn("text/css", css.headers["content-type"])
        self.assertIn("workspace-grid", css.text)
        self.assertIn("entry-screen", css.text)
        self.assertIn("project-row", css.text)
        self.assertIn("project-mode-actions", css.text)
        self.assertIn("project-create-panel", css.text)
        self.assertIn("top-actions", css.text)
        self.assertIn("member-badge", css.text)
        self.assertIn(".hidden", css.text)
        self.assertIn("schema-row", css.text)
        self.assertIn("comment-thread", css.text)
        self.assertEqual(js.status_code, 200)
        self.assertIn("javascript", js.headers["content-type"])
        self.assertIn("loadProjectHome", js.text)
        self.assertIn("createProjectFromGate", js.text)
        self.assertIn("showProjectListMode", js.text)
        self.assertIn("showProjectCreateMode", js.text)
        self.assertIn("renderProjectHome", js.text)
        self.assertIn('apiFetch("/workspaces"', js.text)
        self.assertIn("/workspaces/${encodeURIComponent(workspace.id)}/projects", js.text)
        self.assertIn("/editor-bootstrap", js.text)
        self.assertIn("/schemas", js.text)
        self.assertIn("/schema-matches", js.text)
        self.assertIn("/imports/zip-preview", js.text)
        self.assertIn("/imports/zip-apply", js.text)
        self.assertIn("/projects/${encodeURIComponent(state.projectId)}/members", js.text)
        self.assertIn("/projects/${encodeURIComponent(state.projectId)}/usage", js.text)
        self.assertIn("/auth/signup", js.text)
        self.assertIn("/auth/login", js.text)
        self.assertIn("/auth/logout", js.text)
        self.assertIn("/auth/refresh", js.text)
        self.assertIn("/offline-sync", js.text)
        self.assertIn("/invitations/accept", js.text)
        self.assertIn("/projects/${encodeURIComponent(state.projectId)}/invitations", js.text)
        self.assertIn("/ws/documents/", js.text)
        self.assertIn("merge_strategy", js.text)
        self.assertIn("/collaboration-state", js.text)
        self.assertIn("/presence", js.text)
        self.assertIn("/content-conflict-preview", js.text)
        self.assertIn("/rollback", js.text)
        self.assertIn("URLSearchParams", js.text)
        self.assertIn("navigator.clipboard", js.text)
        self.assertIn("importEditorFile", js.text)
        self.assertIn("keepLocalBufferOnLatest", js.text)
        self.assertIn("previewCreateSchemaMatch", js.text)
        self.assertIn("renderSchema", js.text)
        self.assertIn("SCHEMA_VALIDATION_FAILED", js.text)
        self.assertIn("renderSchemaValidationFailure", js.text)
        self.assertIn("renderZipImportResult", js.text)
        self.assertIn("apiFetchBinary", js.text)
        self.assertIn("renderCollaboration", js.text)
        self.assertIn("buildEditorCursorPath", js.text)
        self.assertIn("findJsonPointerNearOffset", js.text)
        self.assertIn("cursor_path: buildEditorCursorPath()", js.text)
        self.assertIn("cursor_path: payload.cursor_path", js.text)
        self.assertIn("at ${user.cursor_path || \"/\"}", js.text)
        self.assertIn("event.actor_display_name || event.actor_id", js.text)
        self.assertIn("checkpoint.display_name || checkpoint.actor_id", js.text)
        self.assertIn("user.display_name || user.actor_id", js.text)
        self.assertIn("thread.created_by_display_name || thread.created_by", js.text)
        self.assertIn("comment.author_display_name || comment.author_id", js.text)
        self.assertIn("renderInvitationResult", js.text)
        self.assertIn("Invitation email sent", js.text)
        self.assertIn("buildInviteUrl", js.text)
        self.assertIn("clearInviteResult", js.text)
        self.assertIn("copyInviteLink", js.text)
        self.assertIn("Invite link copied", js.text)
        self.assertIn("pendingInviteToken", js.text)
        self.assertIn("invitePromptText", js.text)
        self.assertIn("acceptPendingInvitation", js.text)
        self.assertIn("acceptInvitationToken", js.text)
        self.assertIn("Joining invited project", js.text)
        self.assertIn("renderTeamPanel", js.text)
        self.assertIn("fetchProjectUsageSafe", js.text)
        self.assertIn("formatBytes", js.text)
        self.assertIn("openCollaborationSocket", js.text)
        self.assertIn("openProjectWorkspaceSocket", js.text)
        self.assertIn("sendRealtimeMessage", js.text)
        self.assertIn("sendPresenceHeartbeat", js.text)
        self.assertIn("activePresenceDocumentId", js.text)
        self.assertIn("sendPresenceLeave(state.activePresenceDocumentId || state.selectedDocumentId)", js.text)
        self.assertIn("targetDocumentId || !state.token", js.text)
        self.assertIn("text_session.join", js.text)
        self.assertIn("text_session.commit", js.text)
        self.assertIn("client_operation_id", js.text)
        self.assertIn("newClientOperationId", js.text)
        self.assertIn("idempotent_replay", js.text)
        self.assertIn("authoritativeText", js.text)
        self.assertIn("liveTextPendingOperation", js.text)
        self.assertIn("finishLocalLiveTextOperation", js.text)
        self.assertIn("hasLocalLiveTextBuffer", js.text)
        self.assertIn("scheduleLiveTextDiffIfNeeded", js.text)
        self.assertIn("Live text session rejoined", js.text)
        self.assertIn("Live text session reset to document", js.text)
        self.assertIn("Local buffer preserved and syncing", js.text)
        self.assertIn("liveTextNeedsResync", js.text)
        self.assertIn("session_reset", js.text)
        self.assertIn("markLiveTextOperationUnacknowledged", js.text)
        self.assertIn("resyncLiveTextSessionAfterConflict", js.text)
        self.assertIn("Live text change is still syncing.", js.text)
        self.assertIn("Syncing latest live text before commit.", js.text)
        self.assertIn("flushOfflineQueue", js.text)
        self.assertIn("Autosaved from OpenJson UI", js.text)
        self.assertIn("loadCommentThreads", js.text)
        self.assertIn("comment_threads.updated", js.text)
        self.assertIn("applyCommentThreadsUpdated", js.text)
        self.assertIn("Notes updated.", js.text)
        self.assertIn("document.lifecycle", js.text)
        self.assertIn("applyDocumentLifecycleUpdate", js.text)
        self.assertIn("Local buffer preserved.", js.text)
        self.assertIn("Document restored at version", js.text)
        self.assertIn("/ws/projects/", js.text)
        self.assertIn("project.documents.changed", js.text)
        self.assertIn("applyProjectDocumentsChanged", js.text)
        self.assertIn("Project documents changed. Save or reload", js.text)
        self.assertIn("Project documents updated.", js.text)
        self.assertIn("result.document_id !== state.selectedDocumentId", js.text)
        self.assertIn("createCommentThread", js.text)
        self.assertIn("addCommentReply", js.text)
        self.assertIn("setCommentThreadStatus", js.text)
        self.assertIn("renderCommentThreads", js.text)
        self.assertIn("/comment-threads", js.text)
        self.assertIn("/comments", js.text)
        self.assertIn("/resolve", js.text)
        self.assertIn("/reopen", js.text)
        self.assertIn("handleCreationError", js.text)
        self.assertIn("formatDiagnosticValue", js.text)
        self.assertIn("openjson.userId", js.text)
        self.assertIn("Authorization = `Bearer ${state.token}`", js.text)
        self.assertNotIn("X-Actor-Id", js.text)
        self.assertNotIn("openjson.actorId", js.text)
        self.assertNotIn("connectionForm", js.text)
        self.assertNotIn("actorId", js.text)
        self.assertEqual(favicon.status_code, 200)
        self.assertIn("image/svg", favicon.headers["content-type"])
        self.assertEqual(self._counts(), before)

    def test_static_editor_shell_route_is_registered(self) -> None:
        routes = {(route.path, ",".join(sorted(route.methods))) for route in create_app(self.db_path).routes if hasattr(route, "methods")}

        self.assertIn(("/", "GET"), routes)
        self.assertIn(("/app", "GET"), routes)
        self.assertIn(("/favicon.ico", "GET"), routes)


if __name__ == "__main__":
    unittest.main()
