from __future__ import annotations

from typing import Any


class ErrorCode:
    AUTH_REQUIRED = "AUTH_REQUIRED"
    PERMISSION_DENIED = "PERMISSION_DENIED"
    INVALID_REQUEST = "INVALID_REQUEST"
    ZIP_IMPORT_INVALID = "ZIP_IMPORT_INVALID"
    ZIP_IMPORT_PRECHECK_FAILED = "ZIP_IMPORT_PRECHECK_FAILED"
    PROJECT_MEMBER_ALREADY_EXISTS = "PROJECT_MEMBER_ALREADY_EXISTS"
    PROJECT_MEMBER_NOT_FOUND = "PROJECT_MEMBER_NOT_FOUND"
    API_TOKEN_NOT_FOUND = "API_TOKEN_NOT_FOUND"
    USER_NOT_FOUND = "USER_NOT_FOUND"
    USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS"
    WORKSPACE_NOT_FOUND = "WORKSPACE_NOT_FOUND"
    PROJECT_NOT_FOUND = "PROJECT_NOT_FOUND"
    DOCUMENT_NOT_FOUND = "DOCUMENT_NOT_FOUND"
    INVALID_JSON_SYNTAX = "INVALID_JSON_SYNTAX"
    VERSION_CONFLICT = "VERSION_CONFLICT"
    PATCH_APPLY_FAILED = "PATCH_APPLY_FAILED"
    UNSUPPORTED_PATCH_OPERATION = "UNSUPPORTED_PATCH_OPERATION"
    INVALID_VERSION_RANGE = "INVALID_VERSION_RANGE"
    DOCUMENT_VERSION_NOT_FOUND = "DOCUMENT_VERSION_NOT_FOUND"
    SCHEMA_NOT_FOUND = "SCHEMA_NOT_FOUND"
    SCHEMA_NOT_ACTIVE = "SCHEMA_NOT_ACTIVE"
    INVALID_JSON_SCHEMA = "INVALID_JSON_SCHEMA"
    SCHEMA_VALIDATION_FAILED = "SCHEMA_VALIDATION_FAILED"
    AMBIGUOUS_SCHEMA_MATCH = "AMBIGUOUS_SCHEMA_MATCH"
    SCHEMA_PROJECT_MISMATCH = "SCHEMA_PROJECT_MISMATCH"
    DOCUMENT_HAS_NO_SCHEMA = "DOCUMENT_HAS_NO_SCHEMA"
    COMMENT_THREAD_NOT_FOUND = "COMMENT_THREAD_NOT_FOUND"
    INVALID_COMMENT_ANCHOR = "INVALID_COMMENT_ANCHOR"
    REVIEW_REQUEST_NOT_FOUND = "REVIEW_REQUEST_NOT_FOUND"
    INVALID_REVIEW_STATE = "INVALID_REVIEW_STATE"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    RATE_LIMITED = "RATE_LIMITED"
    REQUEST_BODY_TOO_LARGE = "REQUEST_BODY_TOO_LARGE"
    INTERNAL_ERROR = "INTERNAL_ERROR"


DEFAULT_STATUS_CODES = {
    ErrorCode.AUTH_REQUIRED: 401,
    ErrorCode.PERMISSION_DENIED: 403,
    ErrorCode.INVALID_REQUEST: 400,
    ErrorCode.ZIP_IMPORT_INVALID: 400,
    ErrorCode.ZIP_IMPORT_PRECHECK_FAILED: 400,
    ErrorCode.PROJECT_MEMBER_ALREADY_EXISTS: 409,
    ErrorCode.PROJECT_MEMBER_NOT_FOUND: 404,
    ErrorCode.API_TOKEN_NOT_FOUND: 404,
    ErrorCode.USER_NOT_FOUND: 404,
    ErrorCode.USER_ALREADY_EXISTS: 409,
    ErrorCode.WORKSPACE_NOT_FOUND: 404,
    ErrorCode.PROJECT_NOT_FOUND: 404,
    ErrorCode.DOCUMENT_NOT_FOUND: 404,
    ErrorCode.INVALID_JSON_SYNTAX: 400,
    ErrorCode.VERSION_CONFLICT: 409,
    ErrorCode.PATCH_APPLY_FAILED: 400,
    ErrorCode.UNSUPPORTED_PATCH_OPERATION: 400,
    ErrorCode.INVALID_VERSION_RANGE: 400,
    ErrorCode.DOCUMENT_VERSION_NOT_FOUND: 404,
    ErrorCode.SCHEMA_NOT_FOUND: 404,
    ErrorCode.SCHEMA_NOT_ACTIVE: 400,
    ErrorCode.INVALID_JSON_SCHEMA: 400,
    ErrorCode.SCHEMA_VALIDATION_FAILED: 400,
    ErrorCode.AMBIGUOUS_SCHEMA_MATCH: 400,
    ErrorCode.SCHEMA_PROJECT_MISMATCH: 400,
    ErrorCode.DOCUMENT_HAS_NO_SCHEMA: 400,
    ErrorCode.COMMENT_THREAD_NOT_FOUND: 404,
    ErrorCode.INVALID_COMMENT_ANCHOR: 400,
    ErrorCode.REVIEW_REQUEST_NOT_FOUND: 404,
    ErrorCode.INVALID_REVIEW_STATE: 400,
    ErrorCode.REVIEW_REQUIRED: 403,
    ErrorCode.RATE_LIMITED: 429,
    ErrorCode.REQUEST_BODY_TOO_LARGE: 413,
    ErrorCode.INTERNAL_ERROR: 500,
}


class AppError(Exception):
    def __init__(
        self,
        code: str,
        message: str,
        details: dict[str, Any] | None = None,
        status_code: int | None = None,
    ) -> None:
        super().__init__(message)
        self.code = code
        self.message = message
        self.details = details or {}
        self.status_code = status_code or DEFAULT_STATUS_CODES.get(code, 500)

    def as_response(self) -> dict[str, Any]:
        return {
            "error": {
                "code": self.code,
                "message": self.message,
                "details": self.details,
            }
        }
